#!/usr/bin/env python3

import sys
import click
import os
import configparser

@click.command()
@click.option("--file", "-f", default=f"{os.getcwd()}/taskell.md", help="taskell file to open. Defaults to $(pwd)/taskell.md")
@click.option("--column", "-c", default="To Do", help="Column to show. Defaults to 'To Do'")
def main(file,column):
    if not os.path.isfile(file):
        print("File not found!")
        return
    HOME = os.environ["HOME"]
    config_dirs = [
        f"{HOME}/.taskell",
        f"{os.environ.get('XDG_CONFIG_HOME',HOME + '/.config')}/taskell"
    ]
    config_file = None
    for d in config_dirs:
        ini_path = f"{d}/config.ini"
        if os.path.isfile(ini_path):
            config_file = ini_path
            break
    if config_file is None:
        print("No taskell/config.ini found!")
        return
    config = configparser.ConfigParser()
    config.read(config_file)
    if "markdown" not in config or "title" not in config["markdown"]:
        print("Invalid config.ini: Could not find markdown.title field!")
        return
    title = config["markdown"]["title"]
    if title.startswith('"') and title.endswith('"'):
        title = title[1:-1]
    with open(file, "r") as f:
        parts = f.read().split(title + " ")
        content = next((p for p in parts if p.startswith(column)), None)
    if content is None:
        print("Column not found!")
        return
    # print column content, except the first line containing its name
    print(content[len(column):].strip())


if __name__ == '__main__':
    main()

